name: Build & Test soPres SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    name: Lint & TypeCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint --if-present

      - name: TypeScript Check
        run: npm run typecheck

  build:
    name: Build SDK Packages
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Packages
        run: npm run build:packages

      - name: List Build Outputs
        run: |
          echo "=== @sopres/core ===" 
          ls -lh packages/@sopres/core/dist/ 2>/dev/null || echo "No dist"
          echo "=== @sopres/utils ==="
          ls -lh packages/@sopres/utils/dist/ 2>/dev/null || echo "No dist"
          echo "=== @sopres/sdk ==="
          ls -lh packages/@sopres/sdk/dist/ 2>/dev/null || echo "No dist"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
